installer: offer to configure `init.defaultBranch`
git-for-windows/build-extra pull request #307
Opened 2020-09-29 18:53 UTC by dscho

Since v2.28.0, Git supports `init.defaultBranch` as a way to specify what branch name to use when initializing new repositories. Git for Windows does not have any UI to present that choice to the user. This PR changes that.

Running `./installer/release.sh -d DefaultBranch` in a local check out shows how the page looks like:
![image](https://user-images.githubusercontent.com/127790/94602620-643c7b00-0295-11eb-9cdf-d6262a86f2f6.png)

2020-09-29 19:56 UTC, dscho commented
Through a private conversation, I got some useful feedback which suggested a better wording, which I used to update this PR: 
![image](https://user-images.githubusercontent.com/127790/94609129-aa4a0c80-029e-11eb-9bfc-c17f444ef393.png)

2020-09-29 20:00 UTC, bbolli requested changes

2020-09-29 20:00 UTC, bbolli commented on installer/install.iss
> +    RdbDefaultBranch[DB_Unspecified]:=CreateRadioButton(DefaultBranchPage,'Let Git decide','This leaves it to Git to name the initial branch in newly created repository (current default: "master").',
Missing line wrapping (see screen shot); the label is truncated.

2020-09-29 20:15 UTC, jeffhostetler commented
Seems like we have "master" in the current default parenthetical on the first radio button and then "main" hinted in the text box under the second radio button.  I just worry that a user who is new to the whole controversy is going to wonder why this dialog is here and what is motivating this page.

Where you have "What would you like Git to call the default branch after `git init`?"  could you say something like:
"Historically, the default branch is called `master` following a `git init`; you can now change that!"

2020-09-30 11:15 UTC, dscho commented
@bbolli @jeffhostetler Thank you for your valuable feedback. This is my current version:

![image](https://user-images.githubusercontent.com/127790/94677824-d789cf80-031d-11eb-9ee9-627105c7740a.png)

2020-09-30 12:31 UTC, PhilipOakley commented
LGTM. Thanks.

2020-09-30 14:09 UTC, jeffhostetler commented
Looks good!  Yes, that helps motivate the dialog page.  Thanks!

2020-09-30 14:10 UTC, jeffhostetler approved these changes

2020-09-30 14:37 UTC, derrickstolee commented on installer/install.iss
> +    RdbDefaultBranch[DB_Unspecified]:=CreateRadioButton(DefaultBranchPage,'Let Git decide','Let Git use its default branch name (currently: "master") for the initial branch'+#13+'in newly created rep
It looked like your `currently: "master")` was getting cut off in the picture. How can we make this part get word-wrapped?

2020-09-30 14:37 UTC, derrickstolee commented on installer/install.iss
> +    RdbDefaultBranch[DB_Unspecified]:=CreateRadioButton(DefaultBranchPage,'Let Git decide','Let Git use its default branch name (currently: "master") for the initial branch'+#13+'in newly created rep
Nevermind, you fixed that in a later picture.

2020-09-30 14:38 UTC, derrickstolee approved these changes

2020-09-30 15:20 UTC, dscho commented
Okay, _slightly_ more succinct description for the second bullet point:
![image](https://user-images.githubusercontent.com/127790/94705371-42003700-0341-11eb-91b8-78bac343e439.png)

2020-09-30 19:21 UTC, bbolli approved these changes

2020-09-30 19:32 UTC, merged

2020-10-20 18:55 UTC, the-meme-factory commented
Jesus, this is so fucking retarded

2020-10-20 19:30 UTC, PhilipOakley commented
@the-meme-factory  hmm, civil language please.