git-prompt.sh: remove annoying space when MSYSTEM not set
git-for-windows/build-extra pull request #472
Opened 2023-01-29 18:29 UTC by DRSDavidSoft

Signed-off-by: David Refoua <David@Refoua.me>

This commit removes the annoying double space in the first line of PS1 when `MSYSTEM` is not set.

2023-01-29 20:08 UTC, DRSDavidSoft commented
CI is failing a `sha256sum` checksum

2023-01-30 07:50 UTC, rimrul commented on git-extra/git-prompt.sh
>  	PS1="$PS1"'$MSYSTEM '          # show MSYSTEM
Wouldn't this line need to be removed for this to work?

2023-01-30 08:57 UTC, dscho requested changes

2023-02-21 16:06 UTC, dscho commented
> While I suspect that the use case is broken (because MSYSTEM should always be set), I am open to getting convinced that it makes sense.

This PR has not seen any attempt to motivate the change in the past 3 weeks, therefore I'll close it.

2023-02-21 16:06 UTC, closed without merging